base_locale: cs
locales: ['en', 'cs']

# i18n data storage
data:
  # The default YAML adapter supports reading from and writing to YAML files
  adapter: yaml
  # a list of file globs to read from per-locale
  read: 
    # this one is default:
    - 'config/locales/%{locale}.yml'
    # add this one to also read from namespaced files, e.g. simple_form.en.yml:
    - 'config/locales/*.%{locale}.yml'
  # a list of {key pattern => file} routes, matched top to bottom
  write:
    # this would save all devise keys in it's own file (per locale):
    - ['scroll.*', 'config/locales/scroll.%{locale}.yml']
    - ['notice.*', 'config/locales/notice.%{locale}.yml']
    - ['routes.*', 'config/locales/routes.%{locale}.yml']
    - ['activerecord.*', 'config/locales/activerecord.%{locale}.yml']
    - ['enumerize.*', 'config/locales/enumerize.%{locale}.yml']
    - ['cells.*', 'config/locales/cells.%{locale}.yml']
    # this is the default catch-all:
    - 'config/locales/%{locale}.yml' # path is short for ['*', path]

ignore:
  - app.*